# Homebrew formula for Stillrun (macOS CLI).
# Generated by packaging/render-homebrew-formula.sh.

class Stillrun < Formula
  desc "Command history, safe replay, and launchd-backed jobs for macOS"
  homepage "https://github.com/ingeniousfrog/Stillrun"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/ingeniousfrog/Stillrun/releases/download/v0.1.0/stillrun-aarch64-apple-darwin.tar.gz"
      sha256 "47abb9b079987ce6132be9b19d08a74f0170779a71a1e748b2cf0576cc985dc4"
    end

    on_intel do
      url "https://github.com/ingeniousfrog/Stillrun/releases/download/v0.1.0/stillrun-x86_64-apple-darwin.tar.gz"
      sha256 "637f90bb05e79992b25dddfd469d7734ba5b64f169722e3bc96f887d527b5c5d"
    end
  end

  def install
    bin.install "stillrun"
    generate_completions_from_executable(bin/"stillrun", "completion")
  end

  def caveats
    <<~EOS
      To import existing shell history:
        stillrun import-history --shell auto --preview

      To install the Stillrun shell hook:
        stillrun hook install --shell auto
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/stillrun --version")
    assert_match "history", shell_output("#{bin}/stillrun --help")
  end
end
