# Homebrew formula for Stillrun (macOS CLI).
# Generated by packaging/render-homebrew-formula.sh.

class Stillrun < Formula
  desc "Command history, safe replay, and launchd-backed jobs for macOS"
  homepage "https://github.com/ingeniousfrog/Stillrun"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/ingeniousfrog/Stillrun/releases/download/v0.1.0/stillrun-aarch64-apple-darwin.tar.gz"
      sha256 "61c9283b24f6743f3b85d7cc84dc7e98743df0f5c803976b2166fc7c210bd05d"
    end

    on_intel do
      url "https://github.com/ingeniousfrog/Stillrun/releases/download/v0.1.0/stillrun-x86_64-apple-darwin.tar.gz"
      sha256 "8f89d74f36b31977ac9ac5d8c82ef3b2e2b44f3757647bd242e871dd079ca0e6"
    end
  end

  def install
    bin.install "stillrun"
    generate_completions_from_executable(bin/"stillrun", "completion")
  end

  def caveats
    <<~EOS
      To import existing shell history:
        stillrun import-history --shell auto --preview

      To install the Stillrun shell hook:
        stillrun hook install --shell auto
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/stillrun --version")
    assert_match "history", shell_output("#{bin}/stillrun --help")
  end
end
