#!/usr/bin/env bash
set -euo pipefail

version="${1:?usage: packaging/render-homebrew-formula.sh <version> <aarch64_sha256> <x86_64_sha256> [output]}"
aarch64_sha256="${2:?missing aarch64 sha256}"
x86_64_sha256="${3:?missing x86_64 sha256}"
output="${4:-packaging/homebrew/stillrun.rb}"

if [[ "${version}" == v* ]]; then
  version="${version#v}"
fi

mkdir -p "$(dirname "${output}")"

cat > "${output}" <<RUBY
# Homebrew formula for Stillrun (macOS CLI).
# Generated by packaging/render-homebrew-formula.sh.

class Stillrun < Formula
  desc "Command history, safe replay, and launchd-backed jobs for macOS"
  homepage "https://github.com/ingeniousfrog/Stillrun"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/ingeniousfrog/Stillrun/releases/download/v${version}/stillrun-aarch64-apple-darwin.tar.gz"
      sha256 "${aarch64_sha256}"
    end

    on_intel do
      url "https://github.com/ingeniousfrog/Stillrun/releases/download/v${version}/stillrun-x86_64-apple-darwin.tar.gz"
      sha256 "${x86_64_sha256}"
    end
  end

  def install
    bin.install "stillrun"
    generate_completions_from_executable(bin/"stillrun", "completion")
  end

  def caveats
    <<~EOS
      To import existing shell history:
        stillrun import-history --shell auto --preview

      To install the Stillrun shell hook:
        stillrun hook install --shell auto
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/stillrun --version")
    assert_match "history", shell_output("#{bin}/stillrun --help")
  end
end
RUBY

echo "Wrote ${output}"
